description: Deploying new workers.
heat_template_version: 2013-05-23
outputs:
  server_networks:
    description: The networks of the deployed server
    value:
      get_attr:
      - group_slaves
      - networks
parameters:
  flavor:
    constraints:
    - custom_constraint: nova.flavor
    default: ssc.small
    description: Flavor for the server to be created
    type: string
  image:
    constraints:
    - custom_constraint: glance.image
    default: d0c8f522-ffc7-4224-907d-72145525904e
    description: Image ID or image name to use for the server
    type: string
  key_name:
    constraints:
    - custom_constraint: nova.keypair
    default: team6key
    description: Name of an existing key pair to use for the server
    type: string
  net1:
    constraints:
    - custom_constraint: neutron.network
    default: SNIC 2019/10-32 Internal IPv4 Network
    description: (existing) network for the server to be created
    type: string
  node_count:
    default: 0
    description: Default number of nodes
    type: number
resources:
  group_slaves:
    properties:
      count:
        get_param: node_count
      removal_policies:
      - resource_list:
        - '0'
      resource_def:
        properties:
          flavor:
            get_param: flavor
          image:
            get_param: image
          key_name:
            get_param: key_name
          name: additional_team6_sparkworker%index%
          networks:
          - network:
              get_param: net1
          security_groups:
          - team6
          user_data: "#!/bin/sh\necho \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7MO3V59P1dV0RVzyBtWr8v/N4ND9391MOl2Urv1G3qFx7kob0SLPnr4mpew9xDB+3ZzDPRlFts7eLeTiq4pWpwybeZ40KUnAHKttTli7uhAkBKpHYKMOH7WvuMuHYJjY416KfBj2XulpDdS9Jtue/sWOKDZEF+iP1X6wcIuDDd3WAj5dQ7y+IGmFxgGR4U9/tTgnfVL4scVJKu8M9igHyisHNdr7qDi7Z8yhd4sg/b1EFJ6vmirCjKWWgwprhtmxvhZLjnpTxwzwrccztO9wdlj84L61VFAzKvdIc1nwdNJv3AXVzY38LCjdYqSaaiobZtzKfD+/Ryh6k+PSdLqGB\
            \ ubuntu@team6ansiblehost\" >> /home/ubuntu/.ssh/authorized_keys\napt-get\
            \ update -y\napt-get upgrade -y\n"
          user_data_format: RAW
        type: OS::Nova::Server
    type: OS::Heat::ResourceGroup
